name: app-pipeline

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: run flake8 on the project
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run pytest
        run: PYTHONPATH=. pytest .
      
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: appname
      IMAGE_TAG: ${{ github.sha }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

      - name: add trivy scan for the image
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL
          exit-code: 1

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push image to dockerhub
        run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

      - name: generate metadata
        run: |
          echo '{
            "commit_sha": "${{ github.sha }}",
            "image_tag": "'$DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG'",
            "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
            "pipeline_run_id": "${{ github.run_id }}"
          }' > metadata.json
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: upload metadata to s3
        run: aws s3 cp metadata.json s3://cicd-deploy-metadata-p4/metadata-${{ github.sha }}.json

      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MANIFEST_REPO_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      
      - name: clone manifest repo
        run: |
          git clone git@github.com:VeeraReddyRavuri/app-manifest-repo.git
      
      - name: update image tag
        run: |
          cd app-manifest-repo/k8s
          sed -i "s|image: .*|image: $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG|" deployment.yaml

      - name: configure git
        run: |
          cd app-manifest-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
        
      - name: commit changes
        run: |
          cd app-manifest-repo
          git add .
          git commit -m "update image to $IMAGE_TAG" || echo "no changes"

      - name: push changes
        run: |
          cd app-manifest-repo
          git push origin main

  post_deploy_validate:
    needs: build
    runs-on: ubuntu-latest

    env:
      ALB_DNS: p4-alb-1845188726.ap-south-1.elb.amazonaws.com
    
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: wait for deployment
        run: sleep 60

      - name: shift traffic to 90/10
        run: |
          cat > actions.json <<EOF
          [
            {
              "Type": "forward",
              "ForwardConfig": {
                "TargetGroups": [
                  {
                    "TargetGroupArn": "arn:aws:elasticloadbalancing:ap-south-1:006604849746:targetgroup/p4-blue-tg/ea13d30d202ee2a2",
                    "Weight": 50
                  },
                  {
                    "TargetGroupArn": "arn:aws:elasticloadbalancing:ap-south-1:006604849746:targetgroup/p4-green-tg/e70a979b068c8211",
                    "Weight": 50
                  }
                ]
              }
            }
          ]
          EOF

          aws elbv2 modify-listener \
            --listener-arn arn:aws:elasticloadbalancing:ap-south-1:006604849746:listener/app/p4-alb/89eca7a7a68b632d/c6c1e062642258eb \
            --default-actions file://actions.json
      
      - name: validate deployment
        id: validate
        run: |
          FAILURES=0
          TOTAL=20
          
          for i in {1..20}
          do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://p4-alb-1845188726.ap-south-1.elb.amazonaws.com)

            echo "Attempt $i --> Status: $STATUS"

            if [ "$STATUS" -ne 200 ]; then
              FAILURES=$((FAILURES+1))
            fi

            sleep 2
          done

          echo "Total failures: $FAILURES"

          FAILURE_RATE=$((FAILURES * 100 / TOTAL))

          echo "Failure rate: $FAILURE_RATE%"

          if [ "$FAILURE_RATE" -ge 15 ]; then
            echo "failed=true" >> $GITHUB_OUTPUT
          else
            echo "failed=false" >> $GITHUB_OUTPUT
          fi

      - name: taffic rollback if failed
        if: steps.validate.outputs.failed == 'true'
        run: |
          echo "Rolling back..."

          cat > rollback.json <<EOF
          [
            {
              "Type": "forward",
              "ForwardConfig": {
                "TargetGroups": [
                  {
                    "TargetGroupArn": "arn:aws:elasticloadbalancing:ap-south-1:006604849746:targetgroup/p4-blue-tg/ea13d30d202ee2a2",
                    "Weight": 100
                  },
                  {
                    "TargetGroupArn": "arn:aws:elasticloadbalancing:ap-south-1:006604849746:targetgroup/p4-green-tg/e70a979b068c8211",
                    "Weight": 0
                  }
                ]
              }
            }
          ]
          EOF

          aws elbv2 modify-listener \
            --listener-arn arn:aws:elasticloadbalancing:ap-south-1:006604849746:listener/app/p4-alb/89eca7a7a68b632d/c6c1e062642258eb \
            --default-actions file://rollback.json
      
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MANIFEST_REPO_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: clone manifest repo
        run: |
          git clone git@github.com:VeeraReddyRavuri/app-manifest-repo.git

      - name: revert manifest repo if failed
        if: steps.validate.outputs.failed == 'true'
        run: |
          cd app-manifest-repo

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git revert HEAD --no-edit
          
          git push origin main

      - name: success message
        if: steps.validate.outputs.failed == 'false'
        run: echo "Deployment successful"